---
AWSTemplateFormatVersion: 2010-09-09
Description: SAM Stack

Resources:
  SAMDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sam-deploy-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: !Sub /${AWS::StackName}/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  SAMArtifactBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sensor-stream-sam-artifacts-${AWS::AccountId}-${AWS::Region}
